import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pivot -> Modern Marketing Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `
              var openLidTimeout=500;!function(e,i,o,t){var n=e.createElement("style");n.id=t,n.innerHTML="body { opacity: 0; }",e.head.appendChild(n),i.restoreBodyVisibility=function(){var i=e.getElementById(t);i&&i.parentNode&&i.parentNode.removeChild(i)},setTimeout(i.restoreBodyVisibility,o)}(document,window,openLidTimeout,"openlid-noflicker-style");
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster />
        <Script
          src="https://ab.openlid.io/experiments.js?id=lPhamUDgPfZycJu6unUyUGwwABpxMDWN"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
